### ISSUE TITLE
[Question] Server side only?

### ISSUE THREAD

**Issue by Sir-Will** [CannibalVox/NoTimeFix#1]
hey,

is it possible to have this fixes only on the server or does the client need it to?

**Comment by CannibalVox** [comment]
Only the server.

**Comment by CannibalVox** [comment]
It won't hurt anything if you give it to the client, and giving it to the client means they can open to LAN and get the fix.  So I would recommend pack authors put it on both ends, but server owners running a pack that doesn't include it can drop it in to fix the bugs.

**Comment by CannibalVox** [comment]
BTW, this has only been tested with HQM 4.2.3

**Comment by Sir-Will** [comment]
Okay, thanks!
